### ISSUE TITLE
Error handling in deployFunction swallows errors because of "functionHandler is not defined"

### ISSUE THREAD

**Issue by alexkli** [serverless/serverless-openwhisk#130]
The error handling in deployFunction/index.js [refers to the variable `functionHandler`](https://github.com/serverless/serverless-openwhisk/blob/master/deployFunction/index.js#L71) which is not defined. Thus any error that leads to this catch statement is swallowed:

```
ReferenceError: functionHandler is not defined
    at ow.actions.create.then.catch.err (/Users/alex/Work/code/nui/cli/node_modules/serverless-openwhisk/deployFunction/index.js:71:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by alexkli** [comment]
Unfortunately I don‘t have time right now. One simple way to reproduce it is to

1. set an invalid auth key in `.wskprops` (so that OW requests fail)
2. run a `serverless deploy -f myfunc`
