### ISSUE TITLE
Error when deploying example: SSL wrong version number

### ISSUE THREAD

**Issue by philwinder** [serverless/serverless-openwhisk#133]
Hi there. I've got a problem running the default example on the readme. Here's my setup and what I'm trying to do. Any ideas?

Edit: `wsk ...` also doesn't work. Appears to be something to do with the `kubectl proxy` not proxying https traffic?. Opened issue in main openwhisk repo: https://github.com/apache/incubator-openwhisk-deploy-kube/issues/291

Setup:
Kubernetes on EKS. Openwhisk installed and running. K8s nodeport exposed and proxied to localhost.

Followed instructions:
```
$ serverless create --template openwhisk-nodejs --path my_service
$ cd my_service
$ cat serverless.yml
...
provider:
  name: openwhisk
  ignore_certs: true
functions:
  hello:
    handler: handler.hello
plugins:
  - serverless-openwhisk
npm install
$ export OW_APIHOST=localhost:31001
$ # Default secret
$ export OW_AUTH=23bc46b1-71f6-4ed5-8c54-816aa4f8c502:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP
$ SLS_DEBUG=* serverless deploy
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Compiling Functions...
Serverless: Compiling Packages...
Serverless: Compiling API Gateway definitions...
Serverless: Compiling Rules...
Serverless: Compiling Triggers & Feeds...
Serverless: Compiling Service Bindings...
Serverless: Deploying Functions...

  Serverless Error ---------------------------------------

  Failed to deploy function (my_service-dev-hello) due to error: Unknown Error From API: write EPROTO 140735540790144:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:252:


  Stack Trace --------------------------------------------

ServerlessError: Failed to deploy function (my_service-dev-hello) due to error: Unknown Error From API: write EPROTO 140735540790144:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:252:

    at ow.actions.create.then.catch.err (/Users/phil-mac/source/my_service/node_modules/serverless-openwhisk/deploy/lib/deployFunctions.js:18:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:390:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:421:17)
    at variables.populateService.then.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:157:33)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:144:8)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:43:50)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           10.9.0
     Serverless Version:     1.30.2
```

**Comment by jthomas** [comment]
Hello @philwinder. The framework plugin uses the same HTTP API that the `wsk` CLI uses to interact with the platform. Looks like you've uncovered the problem in that other ticket. 

Once you get the `wsk` tool working, it should just work 🤞.

As this doesn't look like a problem with the framework, would you want to close this and re-open later if you are still having issues once that other one is resolved?
