### ISSUE TITLE
Deploy => API-GW => Bad Request

### ISSUE THREAD

**Issue by bbilger** [serverless/serverless-openwhisk#58]
Hi,
I am rather new to openwhisk, so sorry if I do an obvious mistake.
When I try to deploy any example or just the template, I get a "Bad Request" error (see below) and if I try to deploy an http event handler, the deployment fails completely.

I followed the installation/setup steps from the docs and my `~/.wskprops` file contains APIHOST, APIGW_ACCESS_TOKEN and AUTH.

Do you have any idea what I might do wrong, here?

```
endpoints (api-gw):
 
  Open Whisk Error ---------------------------------------
 
     GET https://openwhisk.ng.bluemix.net/api/v1/experimental/web/whisk.system/routemgmt/getApi.json
     Returned HTTP 400 (Bad Request) --> "Response is not
     valid 'application/json'."
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
OpenWhiskError: GET https://openwhisk.ng.bluemix.net/api/v1/experimental/web/whisk.system/routemgmt/getApi.json Returned HTTP 400 (Bad Request) --> "Response is not valid 'application/json'."
    at Client.handle_errors (/usr/lib/node_modules/serverless-openwhisk/node_modules/openwhisk/lib/client.js:92:11)
    at rp.catch.err (/usr/lib/node_modules/serverless-openwhisk/node_modules/openwhisk/lib/client.js:53:38)
    at tryCatcher (/usr/lib/node_modules/serverless-openwhisk/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/serverless-openwhisk/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/usr/lib/node_modules/serverless-openwhisk/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/usr/lib/node_modules/serverless-openwhisk/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/usr/lib/node_modules/serverless-openwhisk/node_modules/request-promise/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/lib/node_modules/serverless-openwhisk/node_modules/request-promise/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/usr/lib/node_modules/serverless-openwhisk/node_modules/request-promise/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at PluginManager.invoke (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:234:22)
    at PluginManager.run (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:253:17)
    at variables.populateService.then (/usr/lib/node_modules/serverless/lib/Serverless.js:100:33)
    at runCallback (timers.js:672:20)
From previous event:
    at Serverless.run (/usr/lib/node_modules/serverless/lib/Serverless.js:87:74)
    at serverless.init.then (/usr/lib/node_modules/serverless/bin/serverless:23:50)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                 linux
     Node Version:       6.10.3
     Serverless Version: 1.14.0

```

**Comment by kowsikans** [comment]
i get the same error, do you have any solutions?

**Comment by jthomas** [comment]
Hello. 

Unfortunately, I've been delayed getting the new API gateway support finished. The docs were actually updated before I pushed the new release out which supports the new API Gateway. 

I'll hopefully get this finished and released this week. I'll update the ticket when I've pushed the release out so you can re-test.

Apologies!

**Comment by lovellfelix** [comment]
@jthomas any work-around for this in meantime ?

**Comment by jthomas** [comment]
If you unset the `APIGW_ACCESS_TOKEN` is should use the older API GW service by default. This *might* work.

**Comment by lovellfelix** [comment]
@jthomas  Thanks for the prompt response.  I will give it a try.

**Comment by lovellfelix** [comment]
I ended up installing your latest commit and it worked like a charm. 👍  
`npm i serverless/serverless-openwhisk#50f85faa1e340bbd8c528dc3e60b6b47c68a8932  -g`
This will work for me until your next release

**Comment by jthomas** [comment]
Glad to hear, thanks for beta-testing! I'm hoping to push out the official release tomorrow when I've done a bit more testing.

**Comment by bbilger** [comment]
works for me now, thanks!
