### ISSUE TITLE
Sequence Action with Package Individually Won't Deploy

### ISSUE THREAD

**Issue by jthomas** [serverless/serverless-openwhisk#62]
If a user chooses to package functions individually, sequence actions should not require any source files. 

```
service: barry

provider:
  name: openwhisk

package:
  individually: true
  exclude:
    - "**/*"

functions:
  seq:
    sequence:
      - foo
      - bar

plugins:
  - serverless-openwhisk
```

This is failing with the following error:

```
$ SLS_DEBUG='*' serverless deploy
Serverless: Packaging service...

  Serverless Error ---------------------------------------

  No file matches include / exclude patterns

  Stack Trace --------------------------------------------

ServerlessError: No file matches include / exclude patterns
    at Package.zipDirectory (/Users/james/code/bluemix/serverless/lib/plugins/package/lib/zipService.js:45:21)
    at Package.packageFunction (/Users/james/code/bluemix/serverless/lib/plugins/package/lib/packageService.js:77:17)
    at _.map.functionName (/Users/james/code/bluemix/serverless/lib/plugins/package/lib/packageService.js:39:21)
    at arrayMap (/Users/james/code/bluemix/serverless/node_modules/lodash/lodash.js:660:23)
    at Function.map (/Users/james/code/bluemix/serverless/node_modules/lodash/lodash.js:9571:14)
    at Package.packageService (/Users/james/code/bluemix/serverless/lib/plugins/package/lib/packageService.js:34:31)
From previous event:
    at Object.package:createDeploymentArtifacts [as hook] (/Users/james/code/bluemix/serverless/lib/plugins/package/package.js:62:10)
    at BbPromise.reduce (/Users/james/code/bluemix/serverless/lib/classes/PluginManager.js:254:55)
From previous event:
    at PluginManager.invoke (/Users/james/code/bluemix/serverless/lib/classes/PluginManager.js:254:22)
    at PluginManager.spawn (/Users/james/code/bluemix/serverless/lib/classes/PluginManager.js:266:17)
    at Deploy.BbPromise.bind.then (/Users/james/code/bluemix/serverless/lib/plugins/deploy/deploy.js:88:48)
From previous event:
    at Object.before:deploy:deploy [as hook] (/Users/james/code/bluemix/serverless/lib/plugins/deploy/deploy.js:86:8)
    at BbPromise.reduce (/Users/james/code/bluemix/serverless/lib/classes/PluginManager.js:254:55)
From previous event:
    at PluginManager.invoke (/Users/james/code/bluemix/serverless/lib/classes/PluginManager.js:254:22)
    at PluginManager.run (/Users/james/code/bluemix/serverless/lib/classes/PluginManager.js:273:17)
    at variables.populateService.then (/Users/james/code/bluemix/serverless/lib/Serverless.js:105:33)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at Serverless.run (/Users/james/code/bluemix/serverless/lib/Serverless.js:92:74)
    at serverless.init.then (/Users/james/code/bluemix/serverless/bin/serverless:30:50)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           6.9.5
     Serverless Version:     1.15.2
```

**Comment by jthomas** [comment]
cc @bseyb
